SET NAMES 'utf8';
CREATE TABLE IF NOT EXISTS `Suggestions` (
  `ID` varchar(255) NOT NULL,
  `FriendID` varchar(255) NOT NULL,
  FOREIGN KEY (`ID`) REFERENCES Users(`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
